// AUTO-GENERATED by build.rs — do not edit

pub fn load_ftl(locale: &str) -> &'static str {
    match locale {
        "de" => include_str!("../locales/de/main.ftl"),
        "en" => include_str!("../locales/en/main.ftl"),
        "ja" => include_str!("../locales/ja/main.ftl"),
        _ => include_str!("../locales/en/main.ftl"),
    }
}

pub fn detect_locale() -> &'static str {
    for var in &["LC_ALL", "LC_MESSAGES", "LANG"] {
        if let Ok(val) = std::env::var(var) {
            let val_lower = val.to_ascii_lowercase();
            if locale_matches(&val_lower, "de") {
                return "de";
            }
            if locale_matches(&val_lower, "en") {
                return "en";
            }
            if locale_matches(&val_lower, "ja") {
                return "ja";
            }
        }
    }
    "en"
}

fn locale_matches(val: &str, lang: &str) -> bool {
    *val == *lang
        || val
            .strip_prefix(lang)
            .is_some_and(|rest| rest.starts_with(['_', '-', '.', '@']))
}
