use std::fs;
use std::path::Path;

fn main() {
    let locales_dir = Path::new("locales");
    let mut locales: Vec<(String, String)> = Vec::new();

    if let Ok(entries) = fs::read_dir(locales_dir) {
        for entry in entries.flatten() {
            if entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
                if let Ok(code) = entry.file_name().into_string() {
                    let display =
                        locale_display_from_ftl(&locales_dir.join(&code).join("main.ftl"), &code);
                    locales.push((code, display));
                }
            }
        }
    }

    locales.sort_by(|a, b| a.0.cmp(&b.0));

    let dest = Path::new("src").join("locales_codegen.rs");
    let mut code = String::from("// AUTO-GENERATED by build.rs — do not edit\n\n");

    // FTL loader
    code.push_str("pub fn load_ftl(locale: &str) -> &'static str {\n");
    code.push_str("    match locale {\n");
    for (c, _) in &locales {
        code.push_str(&format!(
            "        \"{}\" => include_str!(\"../locales/{}/main.ftl\"),\n",
            c, c
        ));
    }
    code.push_str("        _ => include_str!(\"../locales/en/main.ftl\"),\n");
    code.push_str("    }\n}\n\n");

    // detect_locale
    code.push_str("pub fn detect_locale() -> &'static str {\n");
    code.push_str("    for var in &[\"LC_ALL\", \"LC_MESSAGES\", \"LANG\"] {\n");
    code.push_str("        if let Ok(val) = std::env::var(var) {\n");
    code.push_str("            let val_lower = val.to_ascii_lowercase();\n");
    for (c, _) in &locales {
        code.push_str(&format!(
            "            if locale_matches(&val_lower, \"{}\") {{\n",
            c
        ));
        code.push_str(&format!("                return \"{}\";\n", c));
        code.push_str("            }\n");
    }
    code.push_str("        }\n    }\n    \"en\"\n}\n\n");

    code.push_str("fn locale_matches(val: &str, lang: &str) -> bool {\n");
    code.push_str("    *val == *lang\n");
    code.push_str("        || val\n");
    code.push_str("            .strip_prefix(lang)\n");
    code.push_str("            .is_some_and(|rest| rest.starts_with(['_', '-', '.', '@']))\n");
    code.push_str("}\n");

    fs::write(dest, code).unwrap();

    println!("cargo:rerun-if-changed=locales/");
}

fn locale_display_from_ftl(ftl_path: &Path, code: &str) -> String {
    if let Ok(content) = fs::read_to_string(ftl_path) {
        for line in content.lines() {
            if let Some(name) = line.strip_prefix("# locale-name: ") {
                return name.trim().to_string();
            }
        }
    }
    code.to_string()
}
