use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // --- locales_codegen.rs ---
    let locales_dir = Path::new("locales");
    let mut locales: Vec<String> = Vec::new();

    if let Ok(entries) = fs::read_dir(locales_dir) {
        for entry in entries.flatten() {
            if entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
                if let Ok(code) = entry.file_name().into_string() {
                    locales.push(code);
                }
            }
        }
    }

    locales.sort();

    let mut code = String::from("// AUTO-GENERATED by build.rs — do not edit\n\n");

    code.push_str(&format!(
        "pub const AVAILABLE_LOCALES: &[&str] = &{:?};\n\n",
        locales
    ));

    code.push_str("pub fn load_ftl(locale: &str) -> Option<&'static str> {\n");
    code.push_str("    match locale {\n");
    for c in &locales {
        if c != "en" {
            code.push_str(&format!(
                "        \"{}\" => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/locales/{}/main.ftl\"))),\n",
                c, c
            ));
        }
    }
    code.push_str("        _ => None,\n    }\n}\n");

    fs::write(out_dir.join("locales_codegen.rs"), code).unwrap();

    for c in &locales {
        println!("cargo:rerun-if-changed=locales/{}/main.ftl", c);
    }
    println!("cargo:rerun-if-changed=locales/");

    // --- PAM bindgen ---
    println!("cargo:rustc-link-lib=pam");
    println!("cargo:rerun-if-changed=wrapper.h");

    let bindings = bindgen::Builder::default()
        .header("wrapper.h")
        .allowlist_function("pam_.*")
        .override_abi(bindgen::Abi::CUnwind, "^pam_get_authtok$")
        .allowlist_type("pam_.*")
        .allowlist_var("PAM_.*")
        .opaque_type("pam_handle")
        .default_macro_constant_type(bindgen::MacroTypeVariation::Signed)
        .generate()
        .expect("Failed to parse host Linux-PAM headers via libclang");

    bindings
        .write_to_file(out_dir.join("bindings.rs"))
        .expect("Failed to write generated bindings to target output directory");
}
