use std::fs;
use std::path::Path;

fn main() {
    let locales_dir = Path::new("locales");
    let mut locales: Vec<String> = Vec::new();

    if let Ok(entries) = fs::read_dir(locales_dir) {
        for entry in entries.flatten() {
            if entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
                if let Ok(code) = entry.file_name().into_string() {
                    locales.push(code);
                }
            }
        }
    }

    locales.sort();

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("locales_codegen.rs");
    let mut code = String::from("// AUTO-GENERATED by build.rs — do not edit\n\n");

    // Available locales list
    code.push_str(&format!(
        "pub const AVAILABLE_LOCALES: &[&str] = &{:?};\n\n",
        locales
    ));

    // FTL loader
    code.push_str("pub fn load_ftl(locale: &str) -> Option<&'static str> {\n");
    code.push_str("    match locale {\n");
    for c in &locales {
        if c != "en" {
            code.push_str(&format!(
                "        \"{}\" => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/locales/{}/main.ftl\"))),\n",
                c, c
            ));
        }
    }
    code.push_str("        _ => None,\n    }\n}\n");

    fs::write(dest, code).unwrap();

    for c in &locales {
        println!("cargo:rerun-if-changed=locales/{}/main.ftl", c);
    }
    println!("cargo:rerun-if-changed=locales/");
}
