# TapAuth Configuration GUI – Deutsch (de) Fluent Localization
# Auto-generated by l10n discovery agent – 2026-05-22

# ── Application ──
app-title = TapAuth Konfiguration

# ── Button Labels ──
btn-back = Zurück
btn-cancel = Abbrechen
btn-done = Fertig
btn-confirm = Bestätigen
btn-remove = Entfernen
btn-pair-new-device = Neues Gerät koppeln
btn-manage-devices = Geräte verwalten
btn-settings = Einstellungen
btn-save-config = Konfiguration speichern
btn-rotate-csk = Client Symmetric Key rotieren
btn-recover-keys = Schlüssel wiederherstellen (Kopplungen werden gelöscht)

# ── Status Labels ──
label-please-wait = Bitte warten
label-rotating = Rotiere…
label-recovering = Wiederherstellung läuft…
label-recovery-success = Wiederherstellung erfolgreich! Bitte starten Sie den Daemon neu und koppeln Sie die Geräte erneut.
label-recovery-failed = Wiederherstellung fehlgeschlagen: {$error}
label-tpm-error =  {$error}

# ── Page Titles ──
title-main-menu = TapAuth Konfiguration
title-paired-devices = Gekoppelte Geräte
title-settings = Einstellungen

# ── Pairing Screen ──
pairing-title = Geräte-Kopplung
pairing-preparing = Kopplung wird vorbereitet…
pairing-verify-sas-title = Sicherheitscode überprüfen
pairing-compare-code = Vergleichen Sie diesen Code mit dem auf Ihrem Computer:
pairing-sas-ensure-match = Stellen Sie sicher, dass dieser Code auf Ihrem Gerät übereinstimmt:
pairing-completing = Kopplung wird abgeschlossen…
pairing-success = Kopplung erfolgreich!
pairing-failed = Kopplung fehlgeschlagen
pairing-scan-qr = Scannen Sie diesen QR-Code mit Ihrem Telefon
pairing-enter-manually = Oder manuell eingeben:
pairing-device-id = Geräte-ID: {$device_id}

# ── Device List Screen ──
devices-none-for-user = Keine gekoppelten Geräte für aktuellen Benutzer
devices-current-user = Aktueller Benutzer: {$username}
devices-users-list = Benutzer: {$users}{$info}
devices-shared-info =  (geteilt mit {$count} anderem Benutzer{$s})
devices-id-truncated = ID: {$prefix}…{$suffix}

# ── Settings Screen ──
settings-config-section = Konfiguration
settings-hostname-label = Hostname:
settings-hostname-placeholder = Hostname eingeben
settings-udp-port-label = UDP-Port:
settings-udp-port-placeholder = UDP-Port eingeben (Standard: 36692)
settings-security-section = Sicherheit
settings-language-section = Sprache
settings-csk-warning = Warnung: Das Rotieren des CSK macht alle gekoppelten Geräte ungültig.
    Sie müssen diese erneut koppeln.
settings-config-saved = Konfiguration erfolgreich gespeichert.
settings-csk-rotated = CSK erfolgreich rotiert. Alle Kopplungen wurden gelöscht.
settings-error-prefix = Fehler: {$message}
settings-invalid-port = Ungültige Portnummer (muss 1-65535 sein)

# ── System Error Dialogs ──
error-user-missing-title = Systembenutzer fehlt
error-user-missing-message = Der Systembenutzer 'tapauthd' wird benötigt, wurde aber nicht gefunden.

    Dieser Benutzer sollte während der Installation erstellt worden sein.

    Empfohlene Maßnahmen:
    1. Melden Sie sich ab und wieder an (oder starten Sie das System neu)
    2. Versuchen Sie, die Anwendung erneut zu starten

    Falls das Problem weiterhin besteht, müssen Sie den Benutzer manuell erstellen:
        sudo useradd --system --no-create-home tapauthd
