use std::fs;
use std::path::Path;

fn main() {
    let locales_dir = Path::new("locales");
    let mut locales: Vec<String> = Vec::new();

    if let Ok(entries) = fs::read_dir(locales_dir) {
        for entry in entries.flatten() {
            if entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
                if let Ok(name) = entry.file_name().into_string() {
                    locales.push(name);
                }
            }
        }
    }

    locales.sort();

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("locales_list.rs");

    let mut code = String::from("// AUTO-GENERATED by build.rs — do not edit\n");
    code.push_str(&format!(
        "pub const AVAILABLE_LOCALES: &[&str] = &{:?};\n",
        locales
    ));

    fs::write(dest, code).unwrap();

    println!("cargo:rerun-if-changed=locales/");
}
