#!/bin/bash
# Builds and loads bluetooth.ko and hci_vhci.ko kernel modules for virtual BLE testing
# when running on cloud VM kernels (such as Azure/GitHub Actions) where CONFIG_BT is omitted.
set -euo pipefail

echo "==> Setting up Linux kernel virtual Bluetooth (hci_vhci)..."

if [ -w /dev/vhci ] && python3 -c "import os; fd = os.open('/dev/vhci', os.O_RDWR); os.close(fd)" 2>/dev/null; then
    echo "✅ /dev/vhci is already available and writable."
    exit 0
fi

# Try modprobe first (works on kernels that ship hci_vhci)
if sudo modprobe hci_vhci 2>/dev/null; then
    if [ ! -c /dev/vhci ]; then sudo mknod /dev/vhci c 10 137 2>/dev/null || true; fi
    sudo chmod 666 /dev/vhci 2>/dev/null || true
    if [ -w /dev/vhci ] && python3 -c "import os; fd = os.open('/dev/vhci', os.O_RDWR); os.close(fd)" 2>/dev/null; then
        echo "✅ hci_vhci module loaded via modprobe."
        exit 0
    fi
fi

echo "==> /dev/vhci not available. Attempting to build bluetooth + hci_vhci modules for $(uname -r)..."

# Ensure build essentials, kernel headers, and patchutils are installed
sudo apt-get update -qq
sudo apt-get install -y -qq build-essential "linux-headers-$(uname -r)" patchutils wget

HDRS="linux-headers-$(uname -r)"
SRCPKG=$(apt-cache show "$HDRS" 2>/dev/null | sed -n 's/^Source: \([^ ]*\).*/\1/p' | head -1 || true)
SRCVER=$(apt-cache show "$HDRS" 2>/dev/null | sed -n 's/^Source: [^ ]* (\([^)]*\)).*/\1/p' | head -1 || true)
if [ -z "$SRCVER" ]; then
    SRCVER=$(apt-cache show "$HDRS" 2>/dev/null | sed -n 's/^Version: \([^ ]*\).*/\1/p' | head -1 || true)
fi

if [ -z "$SRCPKG" ] || [ -z "$SRCVER" ]; then
    echo "❌ ERROR: Cannot determine source package for $HDRS via apt-cache."
    exit 1
fi

UPSTREAM="${SRCVER%%-*}"
echo "    Kernel source package: $SRCPKG $SRCVER (upstream: $UPSTREAM)"

BUILD_DIR="/lib/modules/$(uname -r)/build"
if [ ! -d "$BUILD_DIR" ]; then
    echo "❌ ERROR: Kernel build headers directory not found at $BUILD_DIR."
    exit 1
fi

WORK_DIR=$(mktemp -d /tmp/bt-vhci-build.XXXXXX)
trap 'rm -rf "$WORK_DIR"' EXIT
cd "$WORK_DIR"

BASE="https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/$SRCPKG/$SRCVER"
ORIG="${SRCPKG}_${UPSTREAM}.orig.tar.gz"
DIFF="${SRCPKG}_${SRCVER}.diff.gz"

echo "    Downloading $ORIG and $DIFF from Launchpad..."
wget -q "$BASE/$ORIG"
wget -q "$BASE/$DIFF"

TOPDIR=$(tar tzf "$ORIG" 2>/dev/null | head -1 | cut -d/ -f1 || true)
if [ -z "$TOPDIR" ]; then
    echo "❌ ERROR: Could not determine top-level directory of $ORIG."
    exit 1
fi

echo "    Extracting Bluetooth sources from $ORIG..."
tar xzf "$ORIG" \
    "$TOPDIR/net/bluetooth" \
    "$TOPDIR/include/net/bluetooth" \
    "$TOPDIR/drivers/bluetooth/hci_vhci.c"

echo "    Applying distro Bluetooth patch hunks..."
zcat "$DIFF" | filterdiff -i '*/net/bluetooth/*' -i '*/include/net/bluetooth/*' -i '*/drivers/bluetooth/hci_vhci.c' > bt.diff || true
if [ -s bt.diff ]; then
    patch -p1 -d "$TOPDIR" --forward < bt.diff >/dev/null 2>&1 || true
fi

# Prepare flat module directory
MOD_DIR="$WORK_DIR/bt-module"
mkdir -p "$MOD_DIR/include/net"

cp "$WORK_DIR/$TOPDIR"/net/bluetooth/*.c "$MOD_DIR/"
cp "$WORK_DIR/$TOPDIR"/net/bluetooth/*.h "$MOD_DIR/"
cp -r "$WORK_DIR/$TOPDIR/include/net/bluetooth" "$MOD_DIR/include/net/"
cp "$WORK_DIR/$TOPDIR/drivers/bluetooth/hci_vhci.c" "$MOD_DIR/"

{
    echo '# Generated by build-kernel-vhci.sh'
    echo 'CONFIG_BT_BREDR=y'
    echo 'CONFIG_BT_LE=y'
    echo 'CONFIG_BT_DEBUGFS=y'
    echo 'CONFIG_BT_MSFTEXT=y'
    echo 'CONFIG_BT_AOSPEXT=y'
    echo 'ccflags-y += -I$(src)/include -DCONFIG_BT_BREDR=1 -DCONFIG_BT_LE=1 -DCONFIG_BT_DEBUGFS=1 -DCONFIG_BT_MSFTEXT=1 -DCONFIG_BT_AOSPEXT=1'
    echo 'obj-m += bluetooth.o hci_vhci.o'
    sed -E '/^obj-\$\(CONFIG_BT_/d' "$WORK_DIR/$TOPDIR/net/bluetooth/Makefile" | grep -vE '^obj-' || true
} > "$MOD_DIR/Kbuild"

echo "    Compiling bluetooth.ko + hci_vhci.ko against $BUILD_DIR..."
if ! make -C "$BUILD_DIR" M="$MOD_DIR" modules -j"$(nproc)" > "$WORK_DIR/build.log" 2>&1; then
    echo "❌ ERROR: Out-of-tree kernel module compilation failed. Full build log:"
    cat "$WORK_DIR/build.log"
    exit 1
fi

echo "    Modules compiled successfully. Installing and loading modules..."
sudo mkdir -p "/lib/modules/$(uname -r)/kernel/drivers/bluetooth"
sudo cp "$MOD_DIR"/*.ko "/lib/modules/$(uname -r)/kernel/drivers/bluetooth/"
sudo depmod -a
sudo modprobe -v hci_vhci || {
    echo "    modprobe failed, falling back to direct insmod..."
    sudo insmod "$MOD_DIR/bluetooth.ko"
    sudo insmod "$MOD_DIR/hci_vhci.ko"
}

if [ ! -c /dev/vhci ]; then sudo mknod /dev/vhci c 10 137; fi
sudo chmod 666 /dev/vhci

if [ -w /dev/vhci ] && python3 -c "import os; fd = os.open('/dev/vhci', os.O_RDWR); os.close(fd)" 2>/dev/null; then
    echo "✅ Successfully built and loaded bluetooth + hci_vhci modules! /dev/vhci is now active and writable."
else
    echo "❌ ERROR: /dev/vhci exists but is not writable."
    ls -la /dev/vhci
    exit 1
fi
