# TapAuth Configuration GUI – English (en) Fluent Localization
# Auto-generated by l10n discovery agent – 2026-05-22

# ── Application ──
app-title = TapAuth

# ── Button Labels ──
btn-back = Back
btn-cancel = Cancel
btn-done = Done
btn-confirm = Confirm
btn-remove = Remove
btn-pair-new-device = Pair New Device
btn-manage-devices = Manage Devices
btn-settings = Settings
btn-save-config = Save Configuration
btn-rotate-csk = Rotate Client Symmetric Key
btn-recover-keys = Recover Keys (Will Clear Pairings)

# ── Status Labels ──
label-please-wait = Please wait
label-rotating = Rotating…
label-recovering = Recovering…
label-recovery-success = Recovery successful! Please restart the daemon and re-pair devices.
label-recovery-failed = Recovery failed: {$error}
label-tpm-error =  {$error}

# ── Page Titles ──
title-main-menu = TapAuth Configuration
title-paired-devices = Paired Devices
title-settings = Settings

# ── Pairing Screen ──
pairing-title = Device Pairing
pairing-preparing = Preparing pairing…
pairing-verify-sas-title = Verify Security Code
pairing-compare-code = Compare this code with the one shown on your computer:
pairing-sas-ensure-match = Ensure this code matches on your device:
pairing-completing = Completing pairing…
pairing-success = Pairing Successful!
pairing-failed = Pairing Failed
pairing-scan-qr = Scan this QR code with your phone
pairing-enter-manually = Or enter manually:
pairing-device-id = Device ID: {$device_id}

# ── Device List Screen ──
devices-none-for-user = No paired devices for current user
devices-current-user = Current user: {$username}
devices-users-list = Users: {$users}{$info}
devices-shared-info =  (shared with {$count} other user{$s})
devices-id-truncated = ID: {$prefix}…{$suffix}

# ── Settings Screen ──
settings-config-section = Configuration
settings-hostname-label = Hostname:
settings-hostname-placeholder = Enter hostname
settings-udp-port-label = UDP Port:
settings-udp-port-placeholder = Enter UDP port (default: 36692)
settings-security-section = Security
settings-language-section = Language
settings-csk-warning = Warning: Rotating CSK will invalidate all paired devices.
    You will need to re-pair them.
settings-config-saved = Configuration saved successfully.
settings-csk-rotated = CSK rotated successfully. All pairings have been cleared.
settings-error-prefix = Error: {$message}
settings-invalid-port = Invalid port number (must be 1-65535)

# ── System Error/Warning Dialogs ──
error-user-missing-title = System User Missing
error-user-missing-message = The 'tapauthd' system user is required but was not found.

    This user should have been created during installation.

    Recommended action:
    1. Log out and log back in (or restart your system)
    2. Try launching the application again

    If the problem persists, you may need to create the user manually:
        sudo useradd --system --no-create-home tapauthd

error-group-missing-title = System Group Missing
error-group-missing-message = The 'tapauthd-clients' system group is required but was not found.

    This group should have been created during installation.

    Recommended action:
    1. Log out and log back in (or restart your system)
    2. Try launching the application again

    If the problem persists, you may need to create the group manually:
        sudo groupadd --system tapauthd-clients

warn-group-missing-title = Group Membership Required
warn-group-missing-message = You are not a member of the 'tapauthd-clients' group.
    Without this membership, you will not be able to communicate with the TapAuth daemon.

    To add yourself to the group, run this command in a terminal:
        sudo usermod -aG tapauthd-clients $USER

    Then log out and log back in for the change to take effect.
    (You can also run 'newgrp tapauthd-clients' in your current session)
