# Type Name             ID   GECOS                             Home directory    Shell
u      tapauthd         -    "TapAuth System Daemon User"      /var/lib/tapauth  /usr/sbin/nologin
g      tapauthd-clients -    -                                 -                 -
