# Type Path                  Mode User     Group            Age Argument
d      /var/lib/tapauth      0700 tapauthd tapauthd         -   -
d      /var/log/tapauth      0755 tapauthd tapauthd         -   -
d      /run/tapauthd         0750 root     tapauthd-clients -   -
